{
 "title": "DBgen Dashboard",
 "time": { "from": "2021-03-09T17:45:32.148Z", "to": "2021-03-09T21:16:43.984Z" },
 "templating": {
  "list": [
   {
    "name": "run",
    "label": "Run  ID",
    "query": "set search_path = $schema;\nselect run_id  as run_id from run \nunion all\nselect 0\norder by 1 desc;"
   },
   {
    "name": "schema",
    "query": "select schemaname \nfrom\npg_catalog.pg_tables pt\nwhere\ntablename = 'etl_steps';"
   },
   { "name": "datasource", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Run Overview",
   "type": "stat",
   "description": "Summary of the status of each etl_step",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "set search_path = $schema;\nselect now() as time, status as metric, count(*) from etl_steps where run = $run group by status order by status;"
    }
   ]
  },
  {
   "title": "Number of Inputs",
   "type": "graph",
   "description": "Number of inputs per etl_step",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "set search_path = $schema;\nselect now() as time, name as \"metric\", avg(n_inputs) as \"value\"\nfrom etl_steps where status = 'completed' and run = $run and rate is not null and rate != 0 group by name,etl_steps.ind order by etl_steps.ind"
    }
   ]
  },
  {
   "title": "Current Run",
   "type": "table",
   "description": "A Detailed Overview of the run with etl_step by etl_step information",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "set search_path = $schema;\nselect\n  row_number() over () as \"Order\",\n\tname,\n\tcase\n\t\twhen status='initialized' then 0\n\t\twhen status='running' then 1\n\t\twhen status='failed' then 2\n\t\twhen status='completed' then 3\n\t\twhen status='excluded' then 4\n\t\telse -1\n\tend as \"status\",\n\tcoalesce(runtime,0)*60 as runtime,\n\tcoalesce(runtime,0)*100/(select sum(runtime) from etl_steps where run = $run) as \"runtime %\",\n\tcoalesce(rate, 0.0) as rate,\n\tcoalesce(n_inputs,0) as n_inputs,\n\terror,\n\tquery\nfrom\n\tetl_steps where run = $run"
    }
   ]
  },
  {
   "title": "Run Times",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "set search_path = $schema;\nselect starttime as time, delta as \"value-2\",run_id::text as metric from run\nwhere delta != 0 order by run_id desc limit 20;"
    }
   ]
  }
 ]
}